//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISC_V_CPU_Emulator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstructionDigitTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstructionDigitTypeResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RISC_V_CPU_Emulator.Properties.InstructionDigitTypeResources", typeof(InstructionDigitTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ----Opcode---- -aq/rl- --------rs2-------  -------rs1-------   -Opcode-    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------Immediate------   -------rs2--------   -------rs1-------   -Opcide-   ---Immediate---    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --------------------CSR------------------    -------rs1-------   -Opcide-    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSR {
            get {
                return ResourceManager.GetString("CSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -----------------------------------------------------OpCode------------------------------------------------------------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FENCE {
            get {
                return ResourceManager.GetString("FENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------------------Opcode-----------------  -------rs1-------   -Opcode-    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FMV {
            get {
                return ResourceManager.GetString("FMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ----------------Immediate---------------    -------rs1-------   -Opcide-    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -------------------------------Immediate-------------------------------    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -----------------------------------------------------OpCode------------------------------------------------------------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --------Opcode-------  -------rs2--------    -------rs1-------  -Opcide-    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -------rs3------- -Op- --------rs2-------    -------rs1-------   -Opcode-    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string R4 {
            get {
                return ResourceManager.GetString("R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --------Opcode-------  -------rs2--------  -------rs1--------  ---rm---    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RF {
            get {
                return ResourceManager.GetString("RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------Immediate------   -------rs2--------   -------rs1-------   -Opcide-   ---Immediate---    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------Opcode---------  ------shamt------    -------rs1-------   -Opcide-    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHIFT {
            get {
                return ResourceManager.GetString("SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -------------------------------Immediate-------------------------------    ------rd--------    -------Opcode-------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
    }
}
